- name: printing variables
  hosts: web
  become: yes
  tasks: #listing variable in different ways
  - name: normal declaration of variables
    ansible.builtin.debug:
    msg: "the COURSE:{{COURSE}},DURATION:{{DURATION}}"
  vars:
    COURSE: "JAVA"
    DURATION: 120hr
    